//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DisplayNewsPanel.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("মোঃ শাকিকুল ইসলাম ***")]
        public string NewsText1 {
            get {
                return ((string)(this["NewsText1"]));
            }
            set {
                this["NewsText1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public string Direction1 {
            get {
                return ((string)(this["Direction1"]));
            }
            set {
                this["Direction1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color ForeColor1 {
            get {
                return ((global::System.Drawing.Color)(this["ForeColor1"]));
            }
            set {
                this["ForeColor1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color BackColor1 {
            get {
                return ((global::System.Drawing.Color)(this["BackColor1"]));
            }
            set {
                this["BackColor1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Font Font1 {
            get {
                return ((global::System.Drawing.Font)(this["Font1"]));
            }
            set {
                this["Font1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int Speed1 {
            get {
                return ((int)(this["Speed1"]));
            }
            set {
                this["Speed1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("মোঃ শাকিকুল ইসলাম ***")]
        public string NewsText2 {
            get {
                return ((string)(this["NewsText2"]));
            }
            set {
                this["NewsText2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public string Direction2 {
            get {
                return ((string)(this["Direction2"]));
            }
            set {
                this["Direction2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color ForeColor2 {
            get {
                return ((global::System.Drawing.Color)(this["ForeColor2"]));
            }
            set {
                this["ForeColor2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color BackColor2 {
            get {
                return ((global::System.Drawing.Color)(this["BackColor2"]));
            }
            set {
                this["BackColor2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Font Font2 {
            get {
                return ((global::System.Drawing.Font)(this["Font2"]));
            }
            set {
                this["Font2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int Speed2 {
            get {
                return ((int)(this["Speed2"]));
            }
            set {
                this["Speed2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TransparentBackColor1 {
            get {
                return ((bool)(this["TransparentBackColor1"]));
            }
            set {
                this["TransparentBackColor1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TransparentBackColor2 {
            get {
                return ((bool)(this["TransparentBackColor2"]));
            }
            set {
                this["TransparentBackColor2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color DateTimeForeColor {
            get {
                return ((global::System.Drawing.Color)(this["DateTimeForeColor"]));
            }
            set {
                this["DateTimeForeColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color DateTimeBackColor {
            get {
                return ((global::System.Drawing.Color)(this["DateTimeBackColor"]));
            }
            set {
                this["DateTimeBackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Font DateTimeFont {
            get {
                return ((global::System.Drawing.Font)(this["DateTimeFont"]));
            }
            set {
                this["DateTimeFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 1")]
        public global::System.Drawing.Point SettingPanelLocation {
            get {
                return ((global::System.Drawing.Point)(this["SettingPanelLocation"]));
            }
            set {
                this["SettingPanelLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LogoLink {
            get {
                return ((string)(this["LogoLink"]));
            }
            set {
                this["LogoLink"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size LogoSize {
            get {
                return ((global::System.Drawing.Size)(this["LogoSize"]));
            }
            set {
                this["LogoSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point LogoLocation {
            get {
                return ((global::System.Drawing.Point)(this["LogoLocation"]));
            }
            set {
                this["LogoLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowLogo {
            get {
                return ((bool)(this["ShowLogo"]));
            }
            set {
                this["ShowLogo"] = value;
            }
        }
    }
}
